# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
 schedule:
 - cron: "0 * * * *"

name: render-test

jobs:
  render:
    name: render-test
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown","knitr"))'
      - name: Render README
        run: Rscript -e 'rmarkdown::render(test.Rmd")'
      - name: commit results
        run: |
        git add test.html
        git commit -m 'Re-build test.Rmd' || echo "No changes to commit"
        git push origin || echo "No changes to commit"