
name: render-test

on:
 schedule:
 - cron: "0 * * * *"


jobs:
  render:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
    
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown","knitr"))'
    
      - name: Render README
        run: Rscript -e 'rmarkdown::render("test.Rmd")'
    
      - name: commit results
        run: |
        git add test.html man/figures/test-*
        git commit -m "Re-build test.Rmd"
        git push origin || echo "No changes to commit"